# Generated by Django 3.2.25 on 2024-10-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_educationlevel_job_jobtype_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='max_salary_range',
            new_name='max_salary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='min_salary_range',
            new_name='min_salary',
        ),
    ]
