# Generated by Django 3.2.25 on 2024-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20241107_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
