# Generated by Django 3.2.25 on 2024-11-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_candidateskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateskill',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='education',
            name='jobseeker',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='jobseeker',
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_skills', models.ManyToManyField(blank=True, related_name='resumes', to='jobs.CandidateSkill')),
                ('educations', models.ManyToManyField(blank=True, related_name='resumes', to='jobs.Education')),
                ('experiences', models.ManyToManyField(blank=True, related_name='resumes', to='jobs.Experience')),
                ('jobseeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_resume', to='jobs.jobseeker')),
            ],
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobseeker_resume', to='jobs.resume'),
        ),
    ]
