# Generated by Django 3.2.25 on 2024-11-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20241119_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='jobseeker',
        ),
    ]
