# Generated by Django 3.2.25 on 2024-11-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.educationlevel'),
        ),
    ]
