from django.urls import path, include
from .views import (
    RegisterView, 
    UserTypeProfileView, 
    CategoryListView, 
    JobTypeListView, 
    SkillListView, 
    EducationLevelListView, 
    JobCreateAPIView, 
    EmployerJobListAPIView, 
    JobDeleteAPIView, 
    JobSearchAPIView, 
    EmployerProfileAPIView,
    JobUpdateAPIView, 
    JobDetailAPIView, 
    JobSeekerProfileAPIView, 
    ResumeAPIView,
    JobApplicationsListView,
    JobApplicantsAPIView,
    ApplicationStatusUpdateView,
    LogoutAPIView,
    CreateApplicationAPIView)
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    
    path('register/', RegisterView.as_view(), name='register'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('logout/', LogoutAPIView.as_view(), name='logout'),
    path('userTypeProfile/', UserTypeProfileView.as_view(), name='UserTypeProfile'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('job-types/', JobTypeListView.as_view(), name='jobtype-list'),
    path('skills/', SkillListView.as_view(), name='skill-list'),
    path('education-levels/', EducationLevelListView.as_view(), name='educationlevel-list'),
    path('job/<int:pk>/', JobDetailAPIView.as_view(), name='job-detail'),
    path('create-job/', JobCreateAPIView.as_view(), name='create_job'),
    path('edit-job/<int:pk>/', JobUpdateAPIView.as_view(), name='edit-job'),
    path('employer-jobs/', EmployerJobListAPIView.as_view(), name='employer-jobs'),
    path('delete-job/<int:pk>/', JobDeleteAPIView.as_view(), name='job-delete'),
    path('search-jobs/', JobSearchAPIView.as_view(), name='search-jobs'),
    path('employer-profile/', EmployerProfileAPIView.as_view(), name='employer-profile'),
    path("employer-profile/<int:id>/", EmployerProfileAPIView.as_view(), name="employer-profile-id"),
    path('candidate-profile/', JobSeekerProfileAPIView.as_view(), name='candidate-profile'),
    path("candidate-profile/<int:id>/", JobSeekerProfileAPIView.as_view(), name="candidate-profile-id"),
    path('resume/', ResumeAPIView.as_view(), name='resume'),
    path('resume/<int:id>/', ResumeAPIView.as_view(), name='resume-id'),
    path('applications/', JobApplicationsListView.as_view(), name='job_applications_list'),
    path("applications/<int:pk>/", ApplicationStatusUpdateView.as_view(), name="update_application_status"),
    path('job-applicants/<int:job_id>/', JobApplicantsAPIView.as_view(), name='job-applicants'),
    path('apply/', CreateApplicationAPIView.as_view(), name='create-application'),
]